### ISSUE TITLE
Push a new version to crates.io

### ISSUE THREAD

**Issue by pcwalton** [servo/dwrote-rs#14]
Needed for me to put https://github.com/pcwalton/font-kit there.

**Comment by froydnj** [comment]
Pushing a new version would also enable webrender to bump its dwrote dependency to 0.5.0 and remove one of the last remaining crates from Firefox that depends on `winapi` 0.2.8.

**Comment by SimonSapin** [comment]
@nox published https://crates.io/crates/dwrote.
