### ISSUE TITLE
0.5.2 break existing code that use FontFile::new_from_data

### ISSUE THREAD

**Issue by Rhuagh** [servo/dwrote-rs#24]
The api function signature change on FontFile::new_from_data cause existing code to break. 

font-kit broke on Windows because of this. API changes should only be done in minor version updates, not patch versions for this reason. Could you yank yesterdays update and reversion it to 0.6 ?

```
   |
98 |             try!(DWriteFontFile::new_from_data(&**font_data).ok_or(FontLoadingError::Parse));
   |                                                ^^^^^^^^^^^^ expected struct `std::sync::Arc`, found &[u8]
   |
   = note: expected type `std::sync::Arc<std::vec::Vec<u8>>`
              found type `&[u8]`
```

**Comment by Moxinilian** [comment]
This is a critical bug that is preventing the planned release of Amethyst.
Is there any progress on this side?

**Comment by Rhuagh** [comment]
I see that 0.6 is published, could you also please yank 0.5.2?

**Comment by jdm** [comment]
Done.

**Comment by Rhuagh** [comment]
Thanks!

**Comment by Moxinilian** [comment]
Thank you!
