### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by davidhewitt** [servo/dwrote-rs#44]
Many thanks for reviewing and accepting a number of PRs I have prepared recently to enhance some work I was doing on https://github.com/alacritty/alacritty/pull/3127

The Alacritty project maintainers would prefer if these changes were released in a new `dwrote` version before they incorporate the above PR into Alacritty master.

No urgency at all; just wanted to let you know our interest in seeing a new version.

Thanks in advance.

**Comment by jdm** [comment]
Published 0.11.0.
